### PR TITLE
Merge of DAIA and DAIAJSON

### PR DESCRIPTION
**Pull request by lahmann**
Hi Jochen,
I merged both drivers - the merge only adds two methods for xml-parsing which is acceptable imo even though json might become the DAIA standard in the future.
I did also change the ini-settings slightly as the original DAIA-driver had a [DAIA] section and the url was named baseUrl instead of daiaurl - I hope that's fine with you. Apart from legacy support I think that having an explicit DAIA-section in the ini file might help in the future for using the DAIA driver as base for a PAIA driver which would get its settings in a PAIA-section.

Besides: if the ILSException gets thrown upon fail of isSuccess() in doHTTPRequest while processing records in the result-list, all DAIA requests will be shown in the VuFind-frontend with the http-error message. This can happen e.g. if an online-only record gets queried and DAIA(-ILS) responds with an 404 because the record couldn't be found in the ILS. Is this an issue of our DAIA implementation or should the handling of http-errors in the driver be changed?

Alright, let me know if you are ok with this merge - let me know if I can help you.

Best,
André

### CODE REVIEW

**Comment by lahmann** [comment]
Hmm, I just realized that the original DAIA.ini does use the [Global] section - looks like I did introduce the [DAIA] section in my fork on my own. Sorry for that - still I think it might be a good idea to explicitly group DAIA settings in a DAIA section, especially if the DAIA driver should be used as a base for customization and/or a DAIA-PAIA stack.

**Comment by demiankatz** [comment]
If you decide to move settings around, perhaps you could add a fallback that checks Global for things that are missing from DAIA -- that way, people with old .ini files won't get their systems broken.

**Comment by jochen-lienhard** [comment]
Hi Andre,

here some comments.

1) fallback for "Global" (see Demians comment)
2) missing 'daiaidprefix' with commet in DAIA.ini
3) that the http-errors pass to the front-end was not my plan, it only should be in log-files. If you can fix this, that would be nice.

very strange, at the moment it does not work, but it is maybe a problem of the master merge.
I will look for more in the next days.

Greetings

Jochen

**Comment by lahmann** [comment]
Hi Jochen,

ok, I'll work on your comments today and update the pullrequest.

I have some issues with the master merge too - especially the call of the VuFindHttpService in the DAIA driver does not seem to work. When I test the merged DAIA driver on a VuFind2.3.1 branch with your initial CurlAdapter it works fine.

Best,
André

**Comment by lahmann** [comment]
Hi Jochen,

1) done.
2) I copied the DAIAJSON.ini content to DAIA.ini, so there is a daiaidprefix-line plus the comments from DAIAJSON.ini. Am I missing something?
3) An error message is logged to debug-logging now and the doHTTPRequest method now returns false if such error occures: 
- decode_json(false) returns null, so I did not have to touch the JSON-methods
- DOMDocument->loadXML(false) throws a PHP Warning, so I added a check whether the doHTTPRequest returns anything but false for the XML-methods.

I tested the code without the VuFindHTTPService (CurlAdapter) and the VuFind2.3.1 release - it works.

Let me know if you need any further help.

Best,
André

**Comment by demiankatz** [comment]
After merging with master, you should be able to use \VuFindHttp\HttpServiceAwareTrait to avoid redundant definitions in the class for the httpService property and setHttpService method. I'm not sure why merging master would have broken anything, though; as long as you implement the HttpServiceAwareInterface, everything should work.

I'll do some more testing on this end in case my recent refactoring has caused a problem I haven't noticed yet. I'll report back here if I find anything significant.

Either way, please let me know if I can be of any assistance in troubleshooting outstanding problems.

**Comment by lahmann** [comment]
Demian,
I just merged the latest master into this PR and VuFind breaks with the following error:

> Fatal error: Call to undefined method Zend\Http\Client::get() in /usr/local/vufind2/module/VuFind/src/VuFind/ILS/Driver/DAIA.php on line 277

This certainly relates to your comment, but even after using \VuFindHttp\HttpServiceAwareTrait and implementing \VuFindHttp\HttpServiceAwareInterface the error remains. Any clues what's wrong?

Best,
André

**Comment by demiankatz** [comment]
Try clearing your local/cache/configs directory -- if you have an old configuration cached that might cause a problem. If you're still having trouble after that, please let me know.

**Comment by lahmann** [comment]
No change after clearing the cache. I do have some .ini files that are adjusted to my local dev-setup - but I reckon it cannot be an issue with .ini files?

**Comment by demiankatz** [comment]
Looking at the code, I think the problem is that you're calling get() on a Zend\Http\Client object, but you actually want to be calling it on the VuFindHttp\HttpService object. If you just cut out the createClient call and make the get call directly on the service, that might fix everything.

**Comment by lahmann** [comment]
That's it! Thank you very much! :)
I'll clean up my debugging-code and will update the PR.

**Comment by demiankatz** [comment]
Great, glad to help!

**Comment by demiankatz** [comment]
Note that I've just pushed more changes to master that affect the DAIA driver: refactoring to use a new LoggerAwareTrait to reduce redundant logging functionality throughout VuFind. Hopefully it won't cause any conflicts for you.

**Comment by lahmann** [comment]
Demian, thanks for letting me know about the LoggerAwareTrait. I just merged the latest master and this PR locally including your changes for the LoggerAwareTrait and it works fine.
I will update the PR in a minute... Thanks again!

**Comment by demiankatz** [comment]
Glad to help!

**Comment by jochen-lienhard** [comment]
Hmmm ... 
PHP Fatal error:  Trait 'VuFindHttp\HttpServiceAwareTrait' not found
Did you not merge the master?

**Comment by lahmann** [comment]
Oh, sorry - my fault - I'll update the PR with the latest pull from master immediately.

**Comment by lahmann** [comment]
Ok. Done.

**Comment by jochen-lienhard** [comment]
1) Can you please add the change to the DAIA.ini, perhaps you add the prefix only in your local version. Here my idea of the config:

; A default DAIA call looks like this:
; https://daia.myuniversity.edu/?format=json&id=ppn:12345678
;
; The format (json/xml) must be configured in daiaResponseFormat 
; The field which the DAIA server uses to look for must defined by the daiaidprefix
; (it can be for example the ppn: or isbn:)
;
[DAIA]
baseUrl = [your DAIA server base url]
daiaidprefix = "ppn:"
daiaResponseFormat = "json"

; The old configuration still works, but should be replaced be the new one
;[Global]
;baseUrl        = [your DAIA server base url]

I don't believe that your [Global] fallback works correct, because you had to add the format to the url and have no separate response format. Our old DAIA.ini looks like this:
[Global]
baseUrl        = "https://daia.ibs-bw.de/isil/DE-Frei129?format=xml&id=ppn:"

When you will fix this, I will merge the pull request.

@Demian: or do you have some comments for the config?

Greetings

Jochen

**Comment by demiankatz** [comment]
If we're changing the meaning of the baseUrl setting, maybe it would also make sense to rename it to prevent confusion. For example, you could call it hostName to indicate that parameters should not be included. Then, the driver could either encounter baseUrl and parse it into hostName/daiaidprefix/dataResponseFormat, or it could find those three things defined. For extra stability, it could throw an exception if it finds an unexpected configuration combination (like having all four things set, or having key components missing).

**Comment by demiankatz** [comment]
The only disadvantage to using the name "hostname" is that it doesn't quite account for the fact that the user may want to specify http:// or https:// -- we could either add a separate setting to indicate a secure or insecure connection, or else we could allow an optional protocol prefix on the hostname setting (i.e. the user could set "https://daia.myuniversity.edu" or just "daia.myuniversity.edu" -- we should probably default to https if no protocol is specified).

**Comment by lahmann** [comment]
I see your point on renaming baseUrl, on the other hand the DAIA Query API specification (http://gbv.github.io/daiaspec/daia.html#query-api) refers to the baseUrl - changing it to hostName would maybe confuse people even more than sticking with baseUrl. Also, DAIA webservices can have ISILs in their URL path (e.g. "http://daia.gbv.de/isil/{ISIL}") as one DAIA webservice often provides several libraries with availability information.

Anyway, I extended the comments in the DAIA.ini file hoping that this will make things clear for the one setting up the DAIA driver. In addition to that I've introduced a legacy-flag in the DAIA driver which is not very elegant but does ensure that the old DAIA drivers behaviour is kept if a [Global] section is found but the [DAIA] section is not (ie. the record-id gets attached to the baseUrl, no additional params and the DAIA request is sent).

Let me know what you think.

**Comment by demiankatz** [comment]
This seems reasonable to me if Jochen is okay with it! Hopefully we can deprecate the legacy support in the future to simplify the code, but for the moment it is a simple solution.

**Comment by jochen-lienhard** [comment]
It looks good. If there are no other comments, I will merge it.

**Comment by demiankatz** [comment]
Looks good to me, apart from the fact that after the merge, I assume you'll have to eliminate the references to the DAIAJSON driver now that it is integrated into DAIA, and you'll need to move your tests to a different place.

**Comment by jochen-lienhard** [comment]
Can you please update your branch, so that I can merge your pull request?

**Pull request merged**
